version: "3.3"

services:
  web:
    depends_on: 
      - api
    build: 
      context: ./frontend
      dockerfile: Dockerfile.prod
    image: vidly_web:v1.0.0
    ports:
      - 80:3000
    restart: unless-stopped

  api:
    depends_on: 
      - db
    build: ./backend
    image: vidly_api:v1.0.0
    ports:
      - 3001:3001
    environment:
      DB_URL: mongodb://db/vidly
    command: ./docker-entrypoint.sh
    restart: unless-stopped

  db:
    image: mongo:4.0-xenial
    ports:
      - 27017:27017
    volumes:
      - vidly:/data/db
    restart: unless-stopped

volumes:
  vidly: